# Sets default memory used for gradle commands.
org.gradle.jvmargs=-Xmx3G
# ForgeGradle 6 requires running on JDK 17.
org.gradle.java.home=C:/Program Files/Java/jdk-17
org.gradle.java.installations.paths=C:/Program Files/Java/jdk-17
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

# Minecraft / Forge versions
minecraft_version=1.20.1
forge_version=47.4.22

# Mod properties
mod_id=yummy_food
mod_name=美味食物
mod_license=Academic Free License v3.0
mod_version=1.1.4
mod_group_id=net.mcreator.yummyfood
mod_authors=bjkik
